server:
  port: 8765
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: comments-service-id
          uri: lb://comments-service
          predicates:
            - Path=/api/v1/authors/**
            - Path=/api/v1/news/**
          filters:
            - AuthenticationFilter

        - id: news-service-id
          uri: lb://news-service
          predicates:
            - Path=/api/v1/journalists/**
            - Path=/api/v1/news/**
          filters:
            - AuthenticationFilter

        - id: security-service-id
          uri: lb://security-service
          predicates:
            Path=/api/v1/auth/**

  application:
    name: api-gateway



token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: TRACE