server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mista1984gmail/f-task-config.git
          default-label: master
          search-paths: "{application}"
          skip-ssl-validation: true